set_property SRC_FILE_INFO {cfile:{/home/shay/a/zhan4833/SURF Research/rfsoc4x2_flash_poc/4x2_PL_FULL_CONSTRAINTS/4x2_LED_PB__SW.xdc} rfile:../4x2_PL_FULL_CONSTRAINTS/4x2_LED_PB__SW.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{/home/shay/a/zhan4833/SURF Research/rfsoc4x2_flash_poc/4x2_PL_FULL_CONSTRAINTS/clock_constraint.xdc} rfile:../4x2_PL_FULL_CONSTRAINTS/clock_constraint.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR11 [ get_ports "W_LED_0" ]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW10 [ get_ports "W_LED_1" ]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT11 [ get_ports "W_LED_2" ]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM8 [ get_ports "R_LED_0" ]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8 [ get_ports "B_LED_0" ]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR12 [ get_ports "R_LED_1" ]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT10 [ get_ports "B_LED_1" ]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV12 [ get_ports "PB_0" ]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV10 [ get_ports "PB_1" ]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN12 [ get_ports "PB_4" ]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13 [ get_ports "SW_0" ]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU12 [ get_ports "SW_1" ]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM15 [ get_ports sys_clk_100m_p]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN15 [ get_ports sys_clk_100m_n]
